# Generated by Django 4.2.7 on 2023-12-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('water_meter_reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('fixation_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('full_name_creater', models.CharField(max_length=50)),
                ('meter_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'watermeterreading',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('apartment', models.IntegerField()),
                ('house_type', models.CharField(max_length=12)),
                ('meter_reading', models.IntegerField()),
                ('images', models.ImageField(upload_to='')),
                ('address_status', models.CharField(max_length=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='water_meter.users')),
            ],
            options={
                'db_table': 'addresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manytomany',
            fields=[
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='water_meter.addresses')),
                ('water_meter_reading', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='water_meter.watermeterreading')),
            ],
            options={
                'db_table': 'manytomany',
                'managed': True,
                'unique_together': {('address', 'water_meter_reading')},
            },
        ),
    ]
