# Generated by Django 4.2.7 on 2023-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_meter', '0003_alter_addresses_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='images',
            field=models.BinaryField(),
        ),
    ]
